package br.com.curvaeliptica;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

public class MainCurvaElipticaJFrame extends javax.swing.JFrame {

    ArrayList<BigInteger> vListaDePrimos = new ArrayList<BigInteger>();

    public MainCurvaElipticaJFrame(String pTituloJanela) {
        super(pTituloJanela);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        initComponents();
        this.doCarregarComboPrimo();
        this.doLimparCampos();
    }

    private void doCarregarComboPrimo() {
        this.vListaDePrimos = Primo.doGerarPrimosAteh(VG_Constantes._PRIMO_INICIO, VG_Constantes._PRIMO_FIM);
        Object[] tmp_array = this.vListaDePrimos.toArray();
        this.vComboValorP.setModel(new DefaultComboBoxModel(tmp_array));
    }

    private void doLimparCampos() {
        this.doLimparCampoFormula();
        this.doLimparCampoPontos();
        this.doLimparCampoGrupoEliptico();
        this.doLimparCampoOperacoes();
    }

    private void doLimparCampoFormula() {
        this.vTextFieldA.setText("");
        this.vTextFieldB.setText("");
        this.vComboValorP.setSelectedItem(null);
        this.vLabelResultCurvaFormula.setText("Y² = X³ + ? X + ? mod ?");
    }

    private void doLimparCampoPontos() {
        this.vTxtP1X.setText(null);
        this.vTxtP1Y.setText(null);
        this.vTxtP2X.setText(null);
        this.vTxtP2Y.setText(null);
    }

    private void doLimparCampoGrupoEliptico() {
        this.vTxtAreaGrupoEliptico.setText("E? = ?");
        this.vTxtAreaGrupoEliptico.setEditable(false);
    }

    private void doLimparCampoOperacoes() {
        this.vTxtMultiplicador.setText(null);
        this.vTxtAreaPassoAPasso.setText(null);
        this.vTxtAreaPassoAPasso.setEditable(false);
        this.vLabelResultOperacoes.setText("Resposta: ?");
    }
    
    private void doSetRefreshFormula() {
        //this.vLabelResultCurvaFormula.setText("Y² = X³ + " + ((Util.isValidNumber(this.vTextFieldA.getText())) ? this.vTextFieldA.getText() : "?") + " X + " + ((Util.isValidNumber(this.vTextFieldB.getText())) ? this.vTextFieldB.getText() : "?") + " mod " + ((Util.isValidNumber(this.vComboValorP.getSelectedItem().toString())) ? this.vComboValorP.getSelectedItem() : "?"));
        this.vLabelResultCurvaFormula.setText("Y² = X³ + " + ((Util.isValidNumber(this.vTextFieldA.getText())) ? Util.doParentesNumber(this.vTextFieldA.getText()) : "?") + " X + " + ((Util.isValidNumber(this.vTextFieldB.getText())) ? Util.doParentesNumber(this.vTextFieldB.getText()) : "?") + " mod " + ((this.vComboValorP.getSelectedItem() != null) ? this.vComboValorP.getSelectedItem() : "?"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        vPanelInfoCurva = new javax.swing.JPanel();
        vLabelA = new javax.swing.JLabel();
        vTextFieldA = new javax.swing.JTextField();
        vLabelB = new javax.swing.JLabel();
        vTextFieldB = new javax.swing.JTextField();
        vLabelCorpoPrimoP = new javax.swing.JLabel();
        vComboValorP = new javax.swing.JComboBox<>();
        vLabelResultCurvaFormula = new javax.swing.JLabel();
        vPanelPontos = new javax.swing.JPanel();
        vLabelP1pt4 = new javax.swing.JLabel();
        vTxtP1X = new javax.swing.JTextField();
        vLabelP1pt5 = new javax.swing.JLabel();
        vTxtP1Y = new javax.swing.JTextField();
        vLabelP1pt6 = new javax.swing.JLabel();
        vLabelP2pt4 = new javax.swing.JLabel();
        vTxtP2X = new javax.swing.JTextField();
        vLabelP2pt5 = new javax.swing.JLabel();
        vTxtP2Y = new javax.swing.JTextField();
        vLabelP2pt6 = new javax.swing.JLabel();
        vPanelPontosCurva = new javax.swing.JPanel();
        vButtonCalcularFormula = new javax.swing.JButton();
        vLimparTudo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        vTxtAreaGrupoEliptico = new javax.swing.JTextArea();
        vButtonCalcularFormulaCompleto = new javax.swing.JButton();
        vPanelOperacoes = new javax.swing.JPanel();
        vButtonCalcularSoma = new javax.swing.JButton();
        vButtonCalcularSubtracao = new javax.swing.JButton();
        vButtonCalcularMultiplicacao = new javax.swing.JButton();
        vLabelResultOperacoes = new javax.swing.JLabel();
        vPanelCabecalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vTxtMultiplicador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vTxtAreaPassoAPasso = new javax.swing.JTextArea();
        vButonAdd = new javax.swing.JButton();
        vButtonMinus = new javax.swing.JButton();
        vButtonMult = new javax.swing.JButton();
        vLimparResult = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLabelTitulo.setText("Trabalho de Curvas Elipticas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        vPanelInfoCurva.setBorder(javax.swing.BorderFactory.createTitledBorder("Informação da Curva"));

        vLabelA.setText(" A ");

        vTextFieldA.setText("vTxtA");
        vTextFieldA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vTextFieldAActionPerformed(evt);
            }
        });
        vTextFieldA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vTextFieldAKeyReleased(evt);
            }
        });

        vLabelB.setText(" B ");

        vTextFieldB.setText("vTxtB");
        vTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vTextFieldBActionPerformed(evt);
            }
        });
        vTextFieldB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vTextFieldBKeyReleased(evt);
            }
        });

        vLabelCorpoPrimoP.setText("  p ");

        vComboValorP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vComboValorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vComboValorPActionPerformed(evt);
            }
        });

        vLabelResultCurvaFormula.setText("Y² = X³ + ? X + ? mod ?");

        javax.swing.GroupLayout vPanelInfoCurvaLayout = new javax.swing.GroupLayout(vPanelInfoCurva);
        vPanelInfoCurva.setLayout(vPanelInfoCurvaLayout);
        vPanelInfoCurvaLayout.setHorizontalGroup(
            vPanelInfoCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vPanelInfoCurvaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vLabelResultCurvaFormula)
                .addGap(65, 65, 65))
            .addGroup(vPanelInfoCurvaLayout.createSequentialGroup()
                .addGroup(vPanelInfoCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vPanelInfoCurvaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(vLabelA)
                        .addGap(62, 62, 62)
                        .addComponent(vLabelB)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vPanelInfoCurvaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(vPanelInfoCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vComboValorP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vPanelInfoCurvaLayout.createSequentialGroup()
                        .addComponent(vLabelCorpoPrimoP)
                        .addGap(27, 27, 27)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vPanelInfoCurvaLayout.setVerticalGroup(
            vPanelInfoCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vPanelInfoCurvaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vPanelInfoCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vLabelA)
                    .addComponent(vLabelB)
                    .addComponent(vLabelCorpoPrimoP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vPanelInfoCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vComboValorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vLabelResultCurvaFormula)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        vPanelPontos.setBorder(javax.swing.BorderFactory.createTitledBorder("Pontos"));

        vLabelP1pt4.setText("P1 (");

        vTxtP1X.setText("vTxtP1X");

        vLabelP1pt5.setText(" , ");

        vTxtP1Y.setText("vTxtP1Y");

        vLabelP1pt6.setText(" ) ");

        vLabelP2pt4.setText("P2 (");

        vTxtP2X.setText("vTxtP2X");

        vLabelP2pt5.setText(" , ");

        vTxtP2Y.setText("vTxtP2Y");

        vLabelP2pt6.setText(" ) ");

        javax.swing.GroupLayout vPanelPontosLayout = new javax.swing.GroupLayout(vPanelPontos);
        vPanelPontos.setLayout(vPanelPontosLayout);
        vPanelPontosLayout.setHorizontalGroup(
            vPanelPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vPanelPontosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vPanelPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vPanelPontosLayout.createSequentialGroup()
                        .addComponent(vLabelP1pt4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vTxtP1X, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vLabelP1pt5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vTxtP1Y, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vLabelP1pt6))
                    .addGroup(vPanelPontosLayout.createSequentialGroup()
                        .addComponent(vLabelP2pt4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vTxtP2X, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vLabelP2pt5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vTxtP2Y, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vLabelP2pt6)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        vPanelPontosLayout.setVerticalGroup(
            vPanelPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vPanelPontosLayout.createSequentialGroup()
                .addGroup(vPanelPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vLabelP1pt4)
                    .addComponent(vLabelP1pt5)
                    .addComponent(vLabelP1pt6)
                    .addComponent(vTxtP1X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vTxtP1Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vPanelPontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vLabelP2pt4)
                    .addComponent(vLabelP2pt5)
                    .addComponent(vLabelP2pt6)
                    .addComponent(vTxtP2X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vTxtP2Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        vPanelPontosCurva.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo Elíptico"));

        vButtonCalcularFormula.setText("Calcular");
        vButtonCalcularFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonCalcularFormulaActionPerformed(evt);
            }
        });

        vLimparTudo.setText("Limpar TODOS Campos");
        vLimparTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vLimparTudoActionPerformed(evt);
            }
        });

        vTxtAreaGrupoEliptico.setColumns(20);
        vTxtAreaGrupoEliptico.setRows(5);
        vTxtAreaGrupoEliptico.setText("resultado");
        jScrollPane2.setViewportView(vTxtAreaGrupoEliptico);

        vButtonCalcularFormulaCompleto.setText("[Calcular]");
        vButtonCalcularFormulaCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonCalcularFormulaCompletoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vPanelPontosCurvaLayout = new javax.swing.GroupLayout(vPanelPontosCurva);
        vPanelPontosCurva.setLayout(vPanelPontosCurvaLayout);
        vPanelPontosCurvaLayout.setHorizontalGroup(
            vPanelPontosCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vPanelPontosCurvaLayout.createSequentialGroup()
                .addGroup(vPanelPontosCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vPanelPontosCurvaLayout.createSequentialGroup()
                        .addComponent(vButtonCalcularFormula)
                        .addGap(18, 18, 18)
                        .addComponent(vLimparTudo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vButtonCalcularFormulaCompleto))
                    .addGroup(vPanelPontosCurvaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        vPanelPontosCurvaLayout.setVerticalGroup(
            vPanelPontosCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vPanelPontosCurvaLayout.createSequentialGroup()
                .addGroup(vPanelPontosCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vPanelPontosCurvaLayout.createSequentialGroup()
                        .addGroup(vPanelPontosCurvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vButtonCalcularFormula)
                            .addComponent(vLimparTudo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vPanelPontosCurvaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vButtonCalcularFormulaCompleto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        vPanelOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        vButtonCalcularSoma.setText("[+] Soma");
        vButtonCalcularSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonCalcularSomaActionPerformed(evt);
            }
        });

        vButtonCalcularSubtracao.setText("[-] Subtração");
        vButtonCalcularSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonCalcularSubtracaoActionPerformed(evt);
            }
        });

        vButtonCalcularMultiplicacao.setText("[*] multiplicação");
        vButtonCalcularMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonCalcularMultiplicacaoActionPerformed(evt);
            }
        });

        vLabelResultOperacoes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vLabelResultOperacoes.setText("Resposta:  (X3,Y3)");

        jLabel1.setText(" P1 ");

        jLabel2.setText("P1 - P2");

        jLabel3.setText("P1 +  P2");

        vTxtMultiplicador.setText("vTxtMultiplicador");

        vTxtAreaPassoAPasso.setColumns(20);
        vTxtAreaPassoAPasso.setRows(5);
        vTxtAreaPassoAPasso.setText("resultado");
        jScrollPane1.setViewportView(vTxtAreaPassoAPasso);

        vButonAdd.setText("[ + ]");
        vButonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButonAddActionPerformed(evt);
            }
        });

        vButtonMinus.setText("[ - ]");
        vButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonMinusActionPerformed(evt);
            }
        });

        vButtonMult.setText("[ * ]");
        vButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonMultActionPerformed(evt);
            }
        });

        vLimparResult.setText("Limpar");
        vLimparResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vLimparResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vPanelOperacoesLayout = new javax.swing.GroupLayout(vPanelOperacoes);
        vPanelOperacoes.setLayout(vPanelOperacoesLayout);
        vPanelOperacoesLayout.setHorizontalGroup(
            vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                .addGroup(vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2))
                    .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(vButtonCalcularSoma)
                        .addGap(29, 29, 29)
                        .addComponent(vButtonCalcularSubtracao)))
                .addGap(42, 42, 42)
                .addGroup(vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                        .addComponent(vTxtMultiplicador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(vButtonCalcularMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vPanelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                .addGroup(vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vLabelResultOperacoes)
                    .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(vLimparResult)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vButonAdd)
                    .addComponent(vButtonMinus)
                    .addComponent(vButtonMult))
                .addContainerGap())
        );
        vPanelOperacoesLayout.setVerticalGroup(
            vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                .addGroup(vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(vTxtMultiplicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vPanelCabecalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vButtonCalcularMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vButtonCalcularSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vPanelOperacoesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vButtonCalcularSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                                .addComponent(vLabelResultOperacoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vLimparResult))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vPanelOperacoesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(vButonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vButtonMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vButtonMult)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(vPanelPontosCurva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vPanelInfoCurva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vPanelPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(vPanelOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vPanelInfoCurva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vPanelPontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vPanelPontosCurva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vPanelOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setText("[WILLIAM GOULART PACHECO]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(vLabelTitulo))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vComboValorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vComboValorPActionPerformed
        doSetRefreshFormula();
    }//GEN-LAST:event_vComboValorPActionPerformed

    private void vTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vTextFieldBActionPerformed
        doSetRefreshFormula();
    }//GEN-LAST:event_vTextFieldBActionPerformed
 
    private void vTextFieldAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vTextFieldAActionPerformed
        doSetRefreshFormula();
    }//GEN-LAST:event_vTextFieldAActionPerformed

    private void vButtonCalcularFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonCalcularFormulaActionPerformed
        String tmpA = this.vTextFieldA.getText();
        String tmpB = this.vTextFieldB.getText();
        String tmpP = null;

        if (this.vComboValorP.getSelectedItem() != null) {
            tmpP = this.vComboValorP.getSelectedItem().toString();
        }

        if (Util.isNotNull(tmpA, tmpB, tmpP) && Util.isValidNumber(tmpA, tmpB, tmpP)) {
            CurvaEliptica c = new CurvaEliptica(tmpA, tmpB, tmpP);
            List<Ponto> vPontos = c.doGetListaPontosGrupoEliptico_Aula();

            StringBuffer vStrBuffer = new StringBuffer();
            vStrBuffer.append(VG_Constantes._PONTO_INFINITO);

            for (Ponto vPonto : vPontos) {
                vStrBuffer.append(", " + vPonto);
            }

            this.vTxtAreaGrupoEliptico.setText("E" + tmpP + "= { " + vStrBuffer + " }");

        } else {
            this.doLimparCampoGrupoEliptico();
        }
    }//GEN-LAST:event_vButtonCalcularFormulaActionPerformed

    private void vTextFieldBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vTextFieldBKeyReleased
        doSetRefreshFormula();
    }//GEN-LAST:event_vTextFieldBKeyReleased

    private void vTextFieldAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vTextFieldAKeyReleased
        doSetRefreshFormula();
    }//GEN-LAST:event_vTextFieldAKeyReleased

    private void vLimparTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vLimparTudoActionPerformed
        this.doLimparCampos();
    }//GEN-LAST:event_vLimparTudoActionPerformed

    private void vButtonCalcularSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonCalcularSomaActionPerformed
        String vTmpA = this.vTextFieldA.getText();
        String vTmpB = this.vTextFieldB.getText();
        String vTmpP1X = this.vTxtP1X.getText();
        String vTmpP1Y = this.vTxtP1Y.getText();
        String vTmpP2X = this.vTxtP2X.getText();
        String vTmpP2Y = this.vTxtP2Y.getText();
        String vTmpP = null;

        if (this.vComboValorP.getSelectedItem() != null) {
            vTmpP = this.vComboValorP.getSelectedItem().toString();
        }

        if (Util.isNotNull(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpP2X, vTmpP2Y)) {
            if (Util.isValidNumber(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpP2X, vTmpP2Y)) {
                Ponto vP1 = new Ponto(vTmpP1X, vTmpP1Y);
                Ponto vP2 = new Ponto(vTmpP2X, vTmpP2Y);

                VG_Constantes._PASSO_A_PASSO_.doLimparPassoAPasso();
                CurvaEliptica vCurva = new CurvaEliptica(vTmpA, vTmpB, vTmpP);
                Ponto vP3 = vP1.doAdd_Aula(vP2, vCurva);

                if (VG_Constantes._PASSO_A_PASSO_.getStatus().equals(VG_Constantes._STATUS_SEM_ERRO)) {
                    this.vLabelResultOperacoes.setText("Resposta: " + vP3.toString());
                } else {
                    this.vLabelResultOperacoes.setText("Resposta: " + VG_Constantes._PASSO_A_PASSO_.getResultadoFinal());
                }

                this.vTxtAreaPassoAPasso.setText(VG_Constantes._PASSO_A_PASSO_.getPassoApasso());
                System.out.println("-># " + VG_Constantes._PASSO_A_PASSO_.getPassoApasso());

            } else {
                this.doLimparCampoOperacoes();
            }
        } else {
            this.doLimparCampoOperacoes();
        }

    }//GEN-LAST:event_vButtonCalcularSomaActionPerformed

    private void vButtonCalcularSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonCalcularSubtracaoActionPerformed
        String vTmpA = this.vTextFieldA.getText();
        String vTmpB = this.vTextFieldB.getText();
        String vTmpP1X = this.vTxtP1X.getText();
        String vTmpP1Y = this.vTxtP1Y.getText();
        String vTmpP2X = this.vTxtP2X.getText();
        String vTmpP2Y = this.vTxtP2Y.getText();
        String vTmpP = null;

        if (this.vComboValorP.getSelectedItem() != null) {
            vTmpP = this.vComboValorP.getSelectedItem().toString();
        }

        if (Util.isNotNull(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpP2X, vTmpP2Y)) {
            if (Util.isValidNumber(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpP2X, vTmpP2Y)) {
                Ponto vP1 = new Ponto(vTmpP1X, vTmpP1Y);
                Ponto vP2 = new Ponto(vTmpP2X, vTmpP2Y);

                VG_Constantes._PASSO_A_PASSO_.doLimparPassoAPasso();
                CurvaEliptica vCurva = new CurvaEliptica(vTmpA, vTmpB, vTmpP);
                Ponto vP3 = vP1.doSubtrair_Aula(vP2, vCurva);

                if (VG_Constantes._PASSO_A_PASSO_.getStatus().equals(VG_Constantes._STATUS_SEM_ERRO)) {
                    this.vLabelResultOperacoes.setText("Resposta: " + vP3.toString());
                } else {
                    this.vLabelResultOperacoes.setText("Resposta: " + VG_Constantes._PASSO_A_PASSO_.getResultadoFinal());
                }

                this.vTxtAreaPassoAPasso.setText(VG_Constantes._PASSO_A_PASSO_.getPassoApasso());
                System.out.println("-># " + VG_Constantes._PASSO_A_PASSO_.getPassoApasso());

            } else {
                this.doLimparCampoOperacoes();
            }
        } else {
            this.doLimparCampoOperacoes();
        }
    }//GEN-LAST:event_vButtonCalcularSubtracaoActionPerformed

    private void vButtonCalcularMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonCalcularMultiplicacaoActionPerformed
        //doMultiplicar_Aula
        String vTmpA = this.vTextFieldA.getText();
        String vTmpB = this.vTextFieldB.getText();
        String vTmpMultiplicador = this.vTxtMultiplicador.getText();
        String vTmpP1X = this.vTxtP1X.getText();
        String vTmpP1Y = this.vTxtP1Y.getText();
        String vTmpP = null;

        if (this.vComboValorP.getSelectedItem() != null) {
            vTmpP = this.vComboValorP.getSelectedItem().toString();
        }

        if (Util.isNotNull(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpMultiplicador)) {
            if (Util.isValidNumber(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpMultiplicador)) {
                Ponto vP1 = new Ponto(vTmpP1X, vTmpP1Y);

                VG_Constantes._PASSO_A_PASSO_.doLimparPassoAPasso();
                CurvaEliptica vCurva = new CurvaEliptica(vTmpA, vTmpB, vTmpP);
                Ponto vP3 = vP1.doMultiplicar_Aula(vTmpMultiplicador, vCurva);

                if (VG_Constantes._PASSO_A_PASSO_.getStatus().equals(VG_Constantes._STATUS_SEM_ERRO)) {
                    this.vLabelResultOperacoes.setText("Resposta: " + vP3.toString());
                } else {
                    this.vLabelResultOperacoes.setText("Resposta: " + VG_Constantes._PASSO_A_PASSO_.getResultadoFinal());
                }

                this.vTxtAreaPassoAPasso.setText(VG_Constantes._PASSO_A_PASSO_.getPassoApasso());
                System.out.println("-># " + VG_Constantes._PASSO_A_PASSO_.getPassoApasso());

            } else {
                this.doLimparCampoOperacoes();
            }
        } else {
            this.doLimparCampoOperacoes();
        }
    }//GEN-LAST:event_vButtonCalcularMultiplicacaoActionPerformed

    private void vButonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButonAddActionPerformed
        String vTmpA = this.vTextFieldA.getText();
        String vTmpB = this.vTextFieldB.getText();
        String vTmpP1X = this.vTxtP1X.getText();
        String vTmpP1Y = this.vTxtP1Y.getText();
        String vTmpP2X = this.vTxtP2X.getText();
        String vTmpP2Y = this.vTxtP2Y.getText();
        String vTmpP = null;

        if (this.vComboValorP.getSelectedItem() != null) {
            vTmpP = this.vComboValorP.getSelectedItem().toString();
        }

        if (Util.isNotNull(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpP2X, vTmpP2Y)) {
            if (Util.isValidNumber(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpP2X, vTmpP2Y)) {
                Ponto vP1 = new Ponto(vTmpP1X, vTmpP1Y);
                Ponto vP2 = new Ponto(vTmpP2X, vTmpP2Y);

                VG_Constantes._PASSO_A_PASSO_.doLimparPassoAPasso();
                CurvaEliptica vCurva = new CurvaEliptica(vTmpA, vTmpB, vTmpP);
                Ponto vP3 = vP1.doAdd_Completo(vP2, vCurva);

                if (VG_Constantes._PASSO_A_PASSO_.getStatus().equals(VG_Constantes._STATUS_SEM_ERRO)) {
                    this.vLabelResultOperacoes.setText("Resposta: " + vP3.toString());
                } else {
                    this.vLabelResultOperacoes.setText("Resposta: " + VG_Constantes._PASSO_A_PASSO_.getResultadoFinal());
                }

                this.vTxtAreaPassoAPasso.setText(VG_Constantes._PASSO_A_PASSO_.getPassoApasso());
                System.out.println("-># " + VG_Constantes._PASSO_A_PASSO_.getPassoApasso());

            } else {
                this.doLimparCampoOperacoes();
            }
        } else {
            this.doLimparCampoOperacoes();
        }
    }//GEN-LAST:event_vButonAddActionPerformed

    private void vButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonMinusActionPerformed
        String vTmpA = this.vTextFieldA.getText();
        String vTmpB = this.vTextFieldB.getText();
        String vTmpP1X = this.vTxtP1X.getText();
        String vTmpP1Y = this.vTxtP1Y.getText();
        String vTmpP2X = this.vTxtP2X.getText();
        String vTmpP2Y = this.vTxtP2Y.getText();
        String vTmpP = null;

        if (this.vComboValorP.getSelectedItem() != null) {
            vTmpP = this.vComboValorP.getSelectedItem().toString();
        }

        if (Util.isNotNull(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpP2X, vTmpP2Y)) {
            if (Util.isValidNumber(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpP2X, vTmpP2Y)) {
                Ponto vP1 = new Ponto(vTmpP1X, vTmpP1Y);
                Ponto vP2 = new Ponto(vTmpP2X, vTmpP2Y);

                VG_Constantes._PASSO_A_PASSO_.doLimparPassoAPasso();
                CurvaEliptica vCurva = new CurvaEliptica(vTmpA, vTmpB, vTmpP);
                Ponto vP3 = vP1.doSubtrair_Completo(vP2, vCurva);

                if (VG_Constantes._PASSO_A_PASSO_.getStatus().equals(VG_Constantes._STATUS_SEM_ERRO)) {
                    this.vLabelResultOperacoes.setText("Resposta: " + vP3.toString());
                } else {
                    this.vLabelResultOperacoes.setText("Resposta: " + VG_Constantes._PASSO_A_PASSO_.getResultadoFinal());
                }

                this.vTxtAreaPassoAPasso.setText(VG_Constantes._PASSO_A_PASSO_.getPassoApasso());
                System.out.println("-># " + VG_Constantes._PASSO_A_PASSO_.getPassoApasso());

            } else {
                this.doLimparCampoOperacoes();
            }
        } else {
            this.doLimparCampoOperacoes();
        }
    }//GEN-LAST:event_vButtonMinusActionPerformed

    private void vButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonMultActionPerformed
        //doMultiplicar_Aula
        String vTmpA = this.vTextFieldA.getText();
        String vTmpB = this.vTextFieldB.getText();
        String vTmpMultiplicador = this.vTxtMultiplicador.getText();
        String vTmpP1X = this.vTxtP1X.getText();
        String vTmpP1Y = this.vTxtP1Y.getText();
        String vTmpP = null;

        if (this.vComboValorP.getSelectedItem() != null) {
            vTmpP = this.vComboValorP.getSelectedItem().toString();
        }

        if (Util.isNotNull(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpMultiplicador)) {
            if (Util.isValidNumber(vTmpA, vTmpP, vTmpP1X, vTmpP1Y, vTmpMultiplicador)) {
                Ponto vP1 = new Ponto(vTmpP1X, vTmpP1Y);

                VG_Constantes._PASSO_A_PASSO_.doLimparPassoAPasso();
                CurvaEliptica vCurva = new CurvaEliptica(vTmpA, vTmpB, vTmpP);
                Ponto vP3 = vP1.doMultiplicar_Completo(vTmpMultiplicador, vCurva);

                if (VG_Constantes._PASSO_A_PASSO_.getStatus().equals(VG_Constantes._STATUS_SEM_ERRO)) {
                    this.vLabelResultOperacoes.setText("Resposta: " + vP3.toString());
                } else {
                    this.vLabelResultOperacoes.setText("Resposta: " + VG_Constantes._PASSO_A_PASSO_.getResultadoFinal());
                }

                this.vTxtAreaPassoAPasso.setText(VG_Constantes._PASSO_A_PASSO_.getPassoApasso());
                System.out.println("-># " + VG_Constantes._PASSO_A_PASSO_.getPassoApasso());

            } else {
                this.doLimparCampoOperacoes();
            }
        } else {
            this.doLimparCampoOperacoes();
        }
    }//GEN-LAST:event_vButtonMultActionPerformed

    private void vButtonCalcularFormulaCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonCalcularFormulaCompletoActionPerformed
        String tmpA = this.vTextFieldA.getText();
        String tmpB = this.vTextFieldB.getText();
        String tmpP = null;

        if (this.vComboValorP.getSelectedItem() != null) {
            tmpP = this.vComboValorP.getSelectedItem().toString();
        }

        if (Util.isNotNull(tmpA, tmpB, tmpP) && Util.isValidNumber(tmpA, tmpB, tmpP)) {
            CurvaEliptica c = new CurvaEliptica(tmpA, tmpB, tmpP);
            List<Ponto> vPontos = c.doGetListaPontosGrupoEliptico_Completo();

            StringBuffer vStrBuffer = new StringBuffer();
            vStrBuffer.append(VG_Constantes._PONTO_INFINITO);

            for (Ponto vPonto : vPontos) {
                vStrBuffer.append(", " + vPonto);
            }

            this.vTxtAreaGrupoEliptico.setText("E" + tmpP + "= { " + vStrBuffer + " }");

        } else {
            this.doLimparCampoGrupoEliptico();
        }
    }//GEN-LAST:event_vButtonCalcularFormulaCompletoActionPerformed

    private void vLimparResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vLimparResultActionPerformed
        this.vTxtAreaPassoAPasso.setText(null);
        this.vLabelResultOperacoes.setText("Resposta: ?");
    }//GEN-LAST:event_vLimparResultActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton vButonAdd;
    private javax.swing.JButton vButtonCalcularFormula;
    private javax.swing.JButton vButtonCalcularFormulaCompleto;
    private javax.swing.JButton vButtonCalcularMultiplicacao;
    private javax.swing.JButton vButtonCalcularSoma;
    private javax.swing.JButton vButtonCalcularSubtracao;
    private javax.swing.JButton vButtonMinus;
    private javax.swing.JButton vButtonMult;
    private javax.swing.JComboBox<String> vComboValorP;
    private javax.swing.JLabel vLabelA;
    private javax.swing.JLabel vLabelB;
    private javax.swing.JLabel vLabelCorpoPrimoP;
    private javax.swing.JLabel vLabelP1pt4;
    private javax.swing.JLabel vLabelP1pt5;
    private javax.swing.JLabel vLabelP1pt6;
    private javax.swing.JLabel vLabelP2pt4;
    private javax.swing.JLabel vLabelP2pt5;
    private javax.swing.JLabel vLabelP2pt6;
    private javax.swing.JLabel vLabelResultCurvaFormula;
    private javax.swing.JLabel vLabelResultOperacoes;
    private javax.swing.JLabel vLabelTitulo;
    private javax.swing.JButton vLimparResult;
    private javax.swing.JButton vLimparTudo;
    private javax.swing.JPanel vPanelCabecalho;
    private javax.swing.JPanel vPanelInfoCurva;
    private javax.swing.JPanel vPanelOperacoes;
    private javax.swing.JPanel vPanelPontos;
    private javax.swing.JPanel vPanelPontosCurva;
    private javax.swing.JTextField vTextFieldA;
    private javax.swing.JTextField vTextFieldB;
    private javax.swing.JTextArea vTxtAreaGrupoEliptico;
    private javax.swing.JTextArea vTxtAreaPassoAPasso;
    private javax.swing.JTextField vTxtMultiplicador;
    private javax.swing.JTextField vTxtP1X;
    private javax.swing.JTextField vTxtP1Y;
    private javax.swing.JTextField vTxtP2X;
    private javax.swing.JTextField vTxtP2Y;
    // End of variables declaration//GEN-END:variables
}
