algoritmo "Prova_Ex_01"
// Função : TESTAR SE É VOGAL
// Autor : WILLIAM GOULART PACHECO
// Data : 03/10/2012
// Seção de Declarações
var

l:caracter

inicio

escreval("Informe uma letra: ")
leia(l)

escreval(" ---------------------------------------------------- ")
se (l="a") OU (l="e") OU (l="i") OU (l="o") OU (l="u") entao


   escreval(l," é Vogal.")
senao
   escreval(l," não é Vogal.")
fimse


fimalgoritmo
